os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,simplejson,devel,lowest,codecov
    - python: 3.6
      env: TOXENV=docs-html
    - python: 3.5
      env: TOXENV=py,codecov
    - python: 3.4
      env: TOXENV=py,codecov
    - python: nightly
      env: TOXENV=py
  allow_failures:
    - python: nightly
      env: TOXENV=py
  fast_finish: true

script: python3 index.py < testing.txt

cache:
  - pip

branches:
  only:
    - master

after_success:
  - coveralls

notifications:
  email: false
